#!/bin/sh

lb config noauto \
	--apt-http-proxy "http://localhost:3142/" \
	--distribution "wheezy" \
	--architecture "i386" \
	--linux-flavours "486" \
	--binary-images "hdd" \
	--package-lists "lxde" \
	--archive-areas "main contrib non-free" \
	--mirror-bootstrap "http://ftp.uk.debian.org/debian/" \
	--apt-indices false \
	--bootappend-live "locales=en_GB.UTF-8 keyboard-layouts=gb persistent" \
	"${@}"

